version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - ckaznocha
    reviewers:
      - ckaznocha
    commit-message:
      prefix: "automated"
      include: "scope"
  - package-ecosystem: gomod
    directory: /testdata/src/main
    schedule:
      interval: "daily"
    assignees:
      - ckaznocha
    reviewers:
      - ckaznocha
    commit-message:
      prefix: "automated"
      include: "scope"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - ckaznocha
    reviewers:
      - ckaznocha
    commit-message:
      prefix: "automated"
      include: "scope"
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - ckaznocha
    reviewers:
      - ckaznocha
    commit-message:
      prefix: "automated"
      include: "scope"
