name: Govulncheck
on:
  pull_request:
    branches: ["main"]
  merge_group:
    types: [checks_requested]
  schedule:
    - cron: "12 12 * * 1"
  push:
    branches: ["main"]
permissions: read-all
jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit
      - uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee # v1.0.4
        with:
          go-version-file: go.work
          output-format: sarif
          output-file: results.sarif
      - name: "Upload artifact"
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: Govuln SARIF file
          path: results.sarif
          retention-days: 5
          overwrite: true
      - name: "Upload to code-scanning"
        uses: github/codeql-action/upload-sarif@39edc492dbe16b1465b0cafca41432d857bdb31a # v3.29.1
        with:
          sarif_file: results.sarif
